<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageId>FixN</PackageId>
    <Description>32-bit signed fixed point number math</Description>
    <PackageTags>fixed, number, deterministic, rollback, netcode</PackageTags>
  </PropertyGroup>
</Project>
